[package]
name = "absh"
version = "0.0.0"
authors = ["Stiopa Koltsov <stepan.koltsov@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
structopt = "=0.3"
atty = "=0.2"
rand = "0.7.3"
dirs = "3.0.1"
regex = "1.5.4"
wait4 = "=0.1.3"
